default: &default
  appid: <%= Figaro.env.we_id %>
  secret: <%= Figaro.env.we_secret %>
  token:  <%= Figaro.env.wechat_token %>
  encrypt_mode: <%= Figaro.env.wechat_encrypt_mode == "true" %>
  encoding_aes_key: <%= Figaro.env.wechat_encoding_aes_key %>
  trusted_domain_fullname: <%= Figaro.env.wechat_trusted_domain_fullname %>
production:
   <<: *default
development:
  <<: *default


test:
  <<: *default

# Multiple Accounts
#
# wx2_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token2"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket2"
#
# wx2_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx2_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_development:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#  access_token: "tmp/wechat_access_token3"
#  jsapi_ticket: "tmp/wechat_jsapi_ticket3"
#
# wx3_test:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
# wx3_production:
#  <<: *default
#  appid: "my_appid"
#  secret: "my_secret"
#
